// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3GAymzElqO8b1Y38SGslDtKb0-XgnW0',
    appId: '1:567798615189:web:02e42a3e8211ab52e19f9c',
    messagingSenderId: '567798615189',
    projectId: 'dubaothoitiet-50036',
    authDomain: 'dubaothoitiet-50036.firebaseapp.com',
    storageBucket: 'dubaothoitiet-50036.appspot.com',
    measurementId: 'G-XF477WVHJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtWq0AxXshNrSXf8sNWyqv4oQ0blVN02Q',
    appId: '1:567798615189:android:3a11dd64319151bbe19f9c',
    messagingSenderId: '567798615189',
    projectId: 'dubaothoitiet-50036',
    storageBucket: 'dubaothoitiet-50036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt1vVsro82s1KgqQKTJYTfK1LBQkt_gdc',
    appId: '1:567798615189:ios:aec047c0b9631838e19f9c',
    messagingSenderId: '567798615189',
    projectId: 'dubaothoitiet-50036',
    storageBucket: 'dubaothoitiet-50036.appspot.com',
    iosBundleId: 'com.example.thoitietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt1vVsro82s1KgqQKTJYTfK1LBQkt_gdc',
    appId: '1:567798615189:ios:e05b8ad4e7bf4917e19f9c',
    messagingSenderId: '567798615189',
    projectId: 'dubaothoitiet-50036',
    storageBucket: 'dubaothoitiet-50036.appspot.com',
    iosBundleId: 'com.example.thoitietApp.RunnerTests',
  );
}
